name: Build DYLD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    env:
      ARCH: arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set execute permissions for scripts
        run: chmod +x /Users/runner/work/dyld/dyld/build-scripts/configure-dyld-archives.sh

      - name: Build with xcodebuild
        run: xcodebuild -project dyld.xcodeproj OTHER_CFLAGS="-DDYLD_VERSION=852" OTHER_CPLUSPLUSFLAGS="-DDYLD_VERSION=852"
      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dyld-build
          path: build/Release
